[package]
name = "impexls"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
tower-lsp = "0.20.0"
tracing-subscriber = "0.3.19"
